# Generated by Django 2.2.17 on 2021-01-21 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suquiwrites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2021, 1, 21)),
        ),
    ]
