# Generated by Django 2.2.12 on 2021-02-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suquiwrites', '0002_auto_20210203_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='thoughts',
        ),
    ]
