# Generated by Django 2.2.12 on 2021-02-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suquiwrites', '0003_auto_20210203_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-published_date'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
