# Generated by Django 2.2.12 on 2021-02-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suquiwrites', '0005_auto_20210204_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-published_date'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
