# Generated by Django 2.2.12 on 2021-01-29 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suquiwrites', '0006_remove_entry_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 29, 13, 2, 44, 417957, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
